### ISSUE TITLE
#error Unsupported architecture

### ISSUE THREAD

**Issue by JuJin1324** [Philon/macos-crosstools#2]
When I'm using this in CLion and cmake, it occurred below.

/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:784:2: error: #error Unsupported architecture

How can I use this compiler... please.. I need this..

**Comment by JuJin1324** [comment]
I'm using macOS 10.14.6(Mojave) / CLion 2019.3 / This compiler is in Downloads directory.

**Comment by philon** [comment]
@JuJin1324 
Sorry, I've never used Clion, please check the CMakelists. ...are you sure your target platform is armv7?

if you want to test the compiler, like this:

```sh
<compiler_path>/bin/arm-mac-linux-gnueabihf-gcc -o hello hello.c
```

**Comment by JuJin1324** [comment]
I figured it out. It's not gcc's problem. your arm-linux-gcc works fine.
But when I'm using this gcc in CMake, I have to add arm-linux-ld(linker), arm-linux-nm, arm-linux-objdump, arm-linux-objcopy, arm-linux-ranlib, so that It works perfect.
Thank you for your reply!
