### ISSUE TITLE
Request have a guidance for crosstools build from source

### ISSUE THREAD

**Issue by kismeter** [Philon/macos-crosstools#3]
Hi Philon,

Is it possible to have a guidance for the crosstools build from source on MacOS? How to compile https://developer.arm.com/-/media/Files/downloads/gnu-a/10.3-2021.07/srcrel/gcc-arm-src-snapshot-10.3-2021.07.tar.xz with crosstool-NG. Thanks.

**Comment by philon** [comment]
@kismeter 
Did you encounter any problem while compiling？

I suggest refer to [documentation at crosstool-ng website](http://crosstool-ng.github.io/docs/) if it's just how to use the tool, you can customize the version of gcc with `make menuconfig` or `.config` file

**Comment by kismeter** [comment]
@Philon your compile tool works for me, but I hope have chance to customize the toolchain.

**Comment by philon** [comment]
> I suggest refer to [documentation at crosstool-ng website](http://crosstool-ng.github.io/docs/) 

🤷‍♂️so......this is the guidance you need
